# Generated by Django 3.0.8 on 2020-07-28 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='contact',
        ),
    ]
